name: hacker_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  awesome_dio_interceptor: 1.0.0
  dio: 5.1.2
  retrofit: 4.0.1
  google_fonts: 4.0.4
  lottie: 2.3.2
  internet_connection_checker: 1.0.0+1
  connectivity_plus: 4.0.1
  iconsax: 0.0.8
  font_awesome_flutter: 10.4.0
  freezed_annotation: 2.2.0
  intl: 0.18.1
  json_annotation: 4.8.1
  flutter_animate: 4.1.1+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  retrofit_generator: 7.0.1
  build_runner: 2.4.4
  json_serializable: 6.7.0
  freezed: 2.3.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/.env
    - assets/images/
  uses-material-design: true

